server:
  port: 9996

spring:  application:    name: CLOUD-GATEWAY-API

eureka:  client:    register-with-eureka:true
    fetch-registry: true
    service-url:      defaultZone:http://httplocalhost:8761/eureka/
      spring.cloud.gateway.route      

  